spring.application.name=KivuIMSProxyService
server.port=${PORT}
spring.graphql.graphiql.enabled=true
graphiql.mapping=${GRAPHIQL_MAPPING}
graphiql.endpoint.graphql=${GRAPHIQL_ENDPOINT}
identity.base-url=${IDENTITY_BASE_URL}
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
