type Mutation {
    login(input: LoginInput!): LoginResponse
    logout(input: LogoutInput): LogoutResponse
    verifyEmail(input: VerifyEmailInput!): VerifyEmailResponse
    resendVerification(input: ResendVerificationInput!): ResendVerificationResponse
    updateProfile(input: UpdateProfileInput!): UpdateProfileResponse
    forgotPassword(input: ForgotPasswordInput!): ForgotPasswordResponse
    resetPassword(input: ResetPasswordInput!): ResetPasswordResponse
    changePassword(input: ChangePasswordInput!): ChangePasswordResponse
    authorize(input: AuthorizeInput!): AuthorizeResponse
    requestVerificationOtp(input: RequestVerificationOtpInput!): RequestVerificationOtpResponse
    verifyEmailOtp(input: VerifyEmailOtpInput!): VerifyEmailOtpResponse
    register(input: RegisterCompanyInput!): RegisterResponse
    approveCompany(input: ApproveCompanyInput!): ApproveCompanyResponse
    updateCompanyStatus(input: UpdateCompanyStatusInput!): UpdateCompanyStatusResponse
    updateCompanyAdminStatus(input: UpdateCompanyAdminStatusInput!): UpdateCompanyAdminStatusResponse
    updateStore(input: UpdateStoreInput!): UpdateStoreResponse
    createStore(input: CreateStoreInput!): CreateStoreResponse
    assignStoreAdmin(input: AssignStoreAdminInput!): AssignStoreAdminResponse
    updateStoreStatus(input: UpdateStoreStatusInput!): UpdateStoreStatusResponse
    createUser(input: CreateUserInput!): CreateUserResponse
    createSupplier(input: CreateSupplierInput!): CreateSupplierResponse
    updateSupplier(input: UpdateSupplierInput!): UpdateSupplierResponse
    addStoreSupplier(input: AddStoreSupplierInput!): AddStoreSupplierResponse
    removeStoreSupplier(input: RemoveStoreSupplierInput!): RemoveStoreSupplierResponse
    createCustomer(input: CreateCustomerInput!): CreateCustomerResponse
    updateCustomer(input: UpdateCustomerInput!): UpdateCustomerResponse
    deleteCustomer(input: DeleteCustomerInput!): DeleteCustomerResponse
    updateUserRole(input: UpdateUserRoleInput!): UpdateUserRoleResponse
    adminChangePassword(input: AdminChangePasswordInput!): AdminChangePasswordResponse
    adminResetPassword(input: AdminResetPasswordInput!): AdminResetPasswordResponse
    adminResendVerification(input: AdminResendVerificationInput!): AdminResendVerificationResponse
    updateUser(input: UpdateUserInput!): UpdateUserResponse
    deleteUser(input: DeleteUserInput!): DeleteUserResponse
}
