name: NodeJS with Vite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Read-only for build/test steps
      packages: read # Read-only for installing dependencies

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: "@kivunova"
          cache: 'npm'

      - name: Create `.npmrc` for authentication
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc    

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:ci
