export enum AUTH_STATUS {
  UNAUTHENTICATED = "UNAUTHENTICATED",
  AUTHENTICATED = "AUTHENTICATED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TOKEN = "INVALID_TOKEN"
}

export enum LOGOUT_STATUS {
  LOGGED_OUT = "LOGGED_OUT",
  TOKEN_ALREADY_EXPIRED = "TOKEN_ALREADY_EXPIRED"
}
