import { Product, ProductFormData } from "../types/products";
import { ProductStatus } from "../enums/products";

export const DefaultProductFormValues: ProductFormData = {
  name: "",
  productCategory: "",
  productSubcategory: "",
  productSubcategoryItem: "",
  minimumStockThreshold: undefined,
  maximumStockThreshold: undefined,
  leadTime: undefined,
  dailyConsumption: undefined,
  minSalesPrice: undefined,
  purchasePrice: undefined,
  material: "",
  weight: undefined,
  packagingType: "",
  height: undefined,
  width: undefined,
  color: "",
  thickness: undefined,
  packSize: "",
  description: "",
  supplierId: "",
  expirationDate: "",
  productionDate: "",
  brandName: "",
  barcode: "",
  lotNumber: ""
};

export const SampleProducts: Product[] = [
  {
    id: "PROD-001",
    name: "BoomHigh Vape Cartridge",
    productCategory: "Vapes",
    productSubcategory: "Cartridges",
    productSubcategoryItem: "BoomHigh 500mg",
    minimumStockThreshold: 100,
    maximumStockThreshold: 1000,
    leadTime: 7,
    dailyConsumption: 50,
    minSalesPrice: 20.5,
    purchasePrice: 15.0,
    material: "Metal / Glass",
    weight: 0.15,
    packagingType: "Box",
    height: 4.2,
    width: 1.8,
    color: "Silver",
    thickness: 0.5,
    packSize: "10 pcs",
    description:
      "High-quality vape cartridge with smooth airflow and premium flavor.",
    supplierId: "SUP-001",
    expirationDate: "2026-12-31",
    productionDate: "2024-11-01",
    brandName: "BoomHigh",
    barcode: "BHVC-001234",
    lotNumber: "LOT-2024-111",
    status: ProductStatus.ACTIVE,
    storeId: "STORE-001",
    companyId: "COMP-001",
    createdBy: "admin@kivunova.com",
    createdAt: "2025-01-05T10:15:00Z",
    updatedBy: "manager@kivunova.com",
    updatedAt: "2025-02-12T08:30:00Z"
  },
  {
    id: "PROD-002",
    name: "EcoSmart LED Bulb",
    productCategory: "Lighting",
    productSubcategory: "LED Bulbs",
    productSubcategoryItem: "12W Warm White",
    minimumStockThreshold: 200,
    maximumStockThreshold: 1500,
    leadTime: 5,
    dailyConsumption: 80,
    minSalesPrice: 3.99,
    purchasePrice: 2.5,
    material: "Plastic / Aluminum",
    weight: 0.2,
    packagingType: "Blister Pack",
    height: 5.5,
    width: 2.2,
    color: "White",
    thickness: 1.1,
    packSize: "6 pcs",
    description:
      "Energy-efficient LED bulb with 25,000-hour lifespan and warm light tone.",
    supplierId: "SUP-002",
    expirationDate: "2030-01-01",
    productionDate: "2025-03-10",
    brandName: "EcoSmart",
    barcode: "ESLB-008765",
    lotNumber: "LOT-2025-033",
    status: ProductStatus.ACTIVE,
    storeId: "STORE-002",
    companyId: "COMP-001",
    createdBy: "admin@kivunova.com",
    createdAt: "2025-03-10T11:00:00Z",
    updatedBy: "admin@kivunova.com",
    updatedAt: "2025-03-12T15:45:00Z"
  },
  {
    id: "PROD-003",
    name: "KivuNova Gym Bottle",
    productCategory: "Fitness",
    productSubcategory: "Accessories",
    productSubcategoryItem: "Hydration Bottle",
    minimumStockThreshold: 50,
    maximumStockThreshold: 500,
    leadTime: 10,
    dailyConsumption: 15,
    minSalesPrice: 12.0,
    purchasePrice: 8.5,
    material: "BPA-Free Plastic",
    weight: 0.35,
    packagingType: "Plastic Wrap",
    height: 10.0,
    width: 3.5,
    color: "Black",
    thickness: 0.3,
    packSize: "1 pc",
    description:
      "Durable gym bottle with anti-leak cap and ergonomic grip design.",
    supplierId: "SUP-003",
    expirationDate: undefined,
    productionDate: "2025-01-15",
    brandName: "KivuNova",
    barcode: "KNB-009988",
    lotNumber: "LOT-2025-010",
    status: ProductStatus.INACTIVE,
    storeId: "STORE-003",
    companyId: "COMP-002",
    createdBy: "sam@kivunova.com",
    createdAt: "2025-02-01T09:10:00Z",
    updatedBy: "sam@kivunova.com",
    updatedAt: "2025-02-10T12:00:00Z"
  }
];
